@api = http://localhost:3001/Library

GET {{api}}

### update by id
PUT {{api}}/14
Content-Type: application/json

{
    "RateN":"10",
    "Comment":"Unbelivable"
}

###
POST {{api}}
Content-Type: application/json

{
    "RateN":"6",
    "Comment":"hmm nice"
}
### take by id 
GET {{api}}/Name/null

### take by name 
GET {{api}}/3

### take by name 
GET {{api}}/Report2/1/2022-09-1/2022-09-30
### delete by id

DELETE {{api}}/11